### PR TITLE
Update Vuuri.vue, removed console.log

### PR DESCRIPTION
**Pull request by arsen-s**

### CODE REVIEW

**Comment by darkvertex** [comment]
@dannyYassine can this be merged please? 🙏

**Comment by dannyyassine-ce** [comment]
Sorry about that! Let's go.

**Comment by dannyYassine** [comment]
Sorry about that! Let’s go.

**Comment by dannyYassine** [comment]
Im fixing the CI at the moment, ill be publishing these changes soon.

**Pull request merged**
